# Generated by Django 4.0.6 on 2022-07-27 18:44

import uuid

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sms",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("data", models.JSONField()),
                ("context", models.JSONField()),
                ("type", models.CharField(max_length=1000)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_sent", models.DateTimeField(blank=True, null=True)),
                (
                    "sender",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                (
                    "recipient",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "for_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("data", models.JSONField()),
                ("context", models.JSONField()),
                ("type", models.CharField(max_length=1000)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_sent", models.DateTimeField(blank=True, null=True)),
                ("sender", models.EmailField(max_length=1000)),
                ("recipient", models.EmailField(max_length=1000)),
                (
                    "for_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
