# Generated by Django 4.1.1 on 2022-09-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wailer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sms",
            name="sender",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
