# Generated by Django 4.0.1 on 2022-02-08 18:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("wailer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sms",
            name="sender",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
